name: Bazel Build and Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: trinkle23897/envpool-release:2023-01-02-5f1a5fd
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          make bazel-test
      - name: Run clang-tidy
        run: |
          make clang-tidy
